server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        #server-addr: localhost:8848 #配置Nacos地址
        #换成nginx的1111端口，做成集群
        server-addr: 192.168.98.132:1111
management:
  endpoints:
    web:
      exposure:
        include: '*'
